### ISSUE TITLE
get_width() in non-UTF-8 locales

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/utf8#4]
In non-UTF-8 locales R will translate characters it can't display to `"<U+xxxx>"` sequences. Should `utf8_width()` respect this, or maybe we can provide another entry point? This is important for pillar.

``` r
rlang::mut_latin1_locale()
#> Locale codeset is now latin1
"\u6211\u662f\u8c01"
#> [1] "<U+6211><U+662F><U+8C01>"
utf8::get_width("\u6211\u662f\u8c01")
#> Error: 'get_width' is not an exported object from 'namespace:utf8'
```

**Comment by patperry** [comment]
Calling `utf8_width(x, encode = TRUE)` (the default) gives the width of `utf8_encode(x)`, not of `x`:

```r
Sys.setlocale("LC_CTYPE", "C")
cat(utf8_encode("\u6211\u662f\u8c01"), "\n12345678901234567890\n")
#> \u6211\u662f\u8c01 
#> 12345678901234567890
utf8_width("\u6211\u662f\u8c01")
#> [1] 18
```

I would recommend using `utf8_encode(x)` to print with "\u" escapes instead of <U+XXXX>; this makes it easier for the user to copy/paste.

You might think that setting `encode = FALSE` would give you the behavior you want, but right now that function gives `NA` for strings that are not printable in the current locale:

```r
utf8_width("\u6211\u662f\u8c01", encode = FALSE)
#> [1] NA
```

Also, right now the *utf8* package only knows about two locales: C (ASCII-only) and UTF-8. If you're willing to add support for other locales, then I'll accept a PR, but I don't think it's worth the effort. R supports printing UTF-8 on every platform, including both RGui and RStudio on Windows (Well, mostly: on Windows R can't print codepoints above U+FFFF; the *utf8* package escapes these codepoints on Windows). See, e.g., the following screenshot from Windows RGui:

<img width="507" alt="screen shot 2017-11-19 at 6 56 35 pm" src="https://user-images.githubusercontent.com/43450/32997277-82d59640-cd5b-11e7-9b65-1db37d6ad0e4.png">

**Comment by krlmlr** [comment]
I actually pasted the reprex without looking at it, sorry. Here's the corrected version:

``` r
rlang::mut_latin1_locale()
#> Locale codeset is now latin1
"\u6211\u662f\u8c01"
#> [1] "<U+6211><U+662F><U+8C01>"
utf8::utf8_width("\u6211\u662f\u8c01")
#> [1] 6
utf8::utf8_width("\u6211\u662f\u8c01", encode = FALSE)
#> [1] 6
```

The `encode` argument doesn't seem to make a difference in the latin1 locale.

I'm fine with `"\uxxxx"` in values, but for column names it has to be `<U+xxxx>` for consistency with the way foreign column names are processed. I guess I'll just convert these to native and back for printing.

Thanks for mentioning that only C and UTF-8 are supported, this might explain a few peculiarities I see in the automated tests, but not for the printed output. The latter is much more important at this point, but I'd argue that latin1 and some Asian locales are very prevalent on Windows.

**Comment by patperry** [comment]
The reason *utf8* treats all non-`C` locales as UTF-8 is that on Windows it is impossible to set the character locale to UTF-8. RGui and RStudio both support UTF-8 output on Windows, no matter what the declared locale is (see the screenshot above).

I made the choice that it's better to ignore the declared locale and just treat all locales other than `C` as UTF-8. Most non-Windows users will be on UTF-8 locales, and most Windows users would rather not have output restricted to their declared locale.

**Comment by patperry** [comment]
I just put v1.1.0 on CRAN a few minutes ago. See the docs for the new `output_utf8` function for the character locale logic.
