### ISSUE TITLE
Compute width ignoring ANSI sequences

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/utf8#8]
Width computations on strings with ANSI escapes currently consume a very substantial part of the time needed to format tibbles:

![screenshot from 2018-07-04 00-30-04](https://user-images.githubusercontent.com/1741643/42247503-6faf7c84-7f21-11e8-98e5-e916aff950fe.png)

http://rpubs.com/krlmlr/pillar-print-timing

This is even after replacing `crayon::strip_style()` with the faster `fansi::strip_sgr()`. I wonder if UTF-8 could provide a function that computes the width but ignores these non-printable codepoints. I currently can't use `utf8_width()` for this:

``` r
withr::with_options(
  list(crayon.enabled = TRUE),
  utf8::utf8_width(crayon::magenta("four"))
)
#> [1] 24
```

> Created on 2018-07-04 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

CC @brodieG.

**Comment by brodieG** [comment]
@krlmlr the time is taken up by `crayon::italic`, not `fansi::strip_sgr`.  I would recommend just using `sprintf("\033[3m%s\033[23m", string)` for internal time critical code.

![image](https://user-images.githubusercontent.com/6105908/42251294-8a0f132c-7f04-11e8-8273-dfd1c6f32c85.png)

**Comment by brodieG** [comment]
Also, not sure if this is applicable, but `fansi::nchar_ctl(..., type='width')` computes display width ignoring control characters, albeit with all the limitations of `nchar(type='width')`, and some more.

**Comment by krlmlr** [comment]
``` r
crayon:::ansi_regex
#> [1] "(?:(?:\\x{001b}\\[)|\\x{009b})(?:(?:[0-9]{1,3})?(?:(?:;[0-9]{0,3})*)?[A-M|f-m])|\\x{001b}[A-M]"
```

> Created on 2018-07-04 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I'd be fine with the following approximation:

As soon as `\033` or `\733` is encountered, skip everything up to and including the next ASCII character that is in the range of `A-M` or `f-m` or `\0`. (Not sure about `|` as a valid terminator, see https://github.com/r-lib/crayon/commit/7d128804d8a6a45fbaecce461021463062ad921e#r29591062.)

**Comment by brodieG** [comment]
@krlmlr Presumably the two instances are included here:

![image](https://user-images.githubusercontent.com/6105908/42275766-65c37872-7f5f-11e8-932e-a62afe88eba3.png)

If so, again, this is not `fansi::strip_sgr`.  This is happening because you are calling `fansi::strip_sgr(<expression>)`, and `<expression>` itself takes about 300ms to evaluate.  `fansi::strip_sgr` does not call `format_type_sum`.  `format_type_sum` is a `pillar` function.  Presumably, you have some code that implicitly (perhaps via delayed promise evaluation) does something like `fansi::strip_sgr(format_type_sum(...))`.  The only `fansi` code that shows up in the profiler is the `.Call` at the very bottom of the image above.

**According to the data above, the actual time spent evaluating `fansi` code is 20ms**.  In reality it is probably somewhere between 20 and 40 ms since it may just have missed a sampling of the stack dump.

`fansi::strip_sgr` should be faster than the regex.  The regex is basically what `crayon::strip_style` does.

Re width, `nchar(type='width')` main infirimty is that is that it knows nothing of emoji widths.  Since my terminal also doesn't know about emoji widths I have not bothered addressing that at this point.

**Comment by patperry** [comment]
My gut reaction is that this functionality doesn't belong in the `utf8` package. If we add support for ignoring ANSI format annotations to `utf8_width`, then why stop there? Why not support LaTeX and HTML, too? It makes more sense to me that this functionality be part of `fansi`.

I also agree with @brodieG that you can probably get much bigger performance gains by restructuring the `pillar` formatting code. The data frame printing code for the `frame` package (`install_github("patperry/r-frame")`) uses a different formatting strategy and is orders of magnitude faster than `pillar/tibble`:

```
system.time(print(frame::as.dataset(nycflights13::flights)))
# ...
#   user  system elapsed 
#  0.008   0.000   0.008 

system.time(print(nycflights13::flights))
# ...
#   user  system elapsed 
#  0.340   0.002   0.341 
```

(granted, `pillar` does more, so this is not a fair comparison)

`frame` computes the width of each column once, and caches the result. It applies ANSI styling *after* the width computation. Maybe doing something similar would make `pillar` faster?

**Comment by krlmlr** [comment]
@brodieG: You're totally right, adding `force(x)` in `get_extent()` shows where the time is really spent. The profile output is misleading,  The optimization I'm suggesting here will save one allocation and one copy, probably not enough to matter.

@patperry: Thanks for the pointer to _frame_. Formatting columns is extensible via the `pillar_shaft()` generic, and there's code for computing the width without formatting the column. Need to understand better where time is spent, currently it seems to be "fast enough" with default settings but a bit slow if the user asks to print too many columns or rows.
